language: java
sudo: false
jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: orrrg
    token:
      secure: bUMq7V8144PiwD0GdJxF6vHTt6BoAW558IlX9IKEH9dA++oSu7tTacC22gMDBGqwy6SbZWhbU6jK0xSfEyIq34dC5E6D8rZtJPCRvekkmw4GMNyN3uOLDRD6dxjmFIEv8IC4a8bb6H/rQjePQWgSsQQw4HzOMTQzcOWV+KhPhAxhoFbU0J/5VseCBvqnGS6/5to+GTlNXXG5wr/eBsvDSwIXwBqhvwcQZjZRwyichxcw7fG+k1ZHVbjYJptKaqjUgSg2vQ5jXNvGDXyBrb7xXOxP0BYwpA+a+PoQs4mQNqf0j1xOnEBuKhIgDSnbWLItgazQE0zo/EpI1bkoYhCMQlWHLB/B6sgZJ0mrusGYkEuH2Auxfx2dwaigYmkOplrGfyBxv/fU2AAkgxUhSHNE+83Pfb0iSjRznTElQduQVMc01Kkt69sonwyIpGGKSiMnSj9U4Pz1zxLwB2g6txoYybgzodWhDVTYPSUowMgCzbIgKc8TJor3RBvXrCJtC0JHFAaUNzTODBskGEbl6+zTN+Id1cJjaeXtHI/ViLE2oRrquUN6KflTA5iyKHPDiNYYOnybsIxUyyH0pUwoZI3+5JHX5ggXKy1Y9f7n7LXUHwA8l+BlvdS2l7w9EY2cCfwr4toOyQWjolrB4ZYopG9HChlCSx5y2wg5TiewNvanHVA=

script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
- mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
