language: java
sudo: false
jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: orrrg
    token:
      secure: bUMq7V8144PiwD0GdJxF6vHTt6BoAW558IlX9IKEH9dA++oSu7tTacC22gMDBGqwy6SbZWhbU6jK0xSfEyIq34dC5E6D8rZtJPCRvekkmw4GMNyN3uOLDRD6dxjmFIEv8IC4a8bb6H/rQjePQWgSsQQw4HzOMTQzcOWV+KhPhAxhoFbU0J/5VseCBvqnGS6/5to+GTlNXXG5wr/eBsvDSwIXwBqhvwcQZjZRwyichxcw7fG+k1ZHVbjYJptKaqjUgSg2vQ5jXNvGDXyBrb7xXOxP0BYwpA+a+PoQs4mQNqf0j1xOnEBuKhIgDSnbWLItgazQE0zo/EpI1bkoYhCMQlWHLB/B6sgZJ0mrusGYkEuH2Auxfx2dwaigYmkOplrGfyBxv/fU2AAkgxUhSHNE+83Pfb0iSjRznTElQduQVMc01Kkt69sonwyIpGGKSiMnSj9U4Pz1zxLwB2g6txoYybgzodWhDVTYPSUowMgCzbIgKc8TJor3RBvXrCJtC0JHFAaUNzTODBskGEbl6+zTN+Id1cJjaeXtHI/ViLE2oRrquUN6KflTA5iyKHPDiNYYOnybsIxUyyH0pUwoZI3+5JHX5ggXKy1Y9f7n7LXUHwA8l+BlvdS2l7w9EY2cCfwr4toOyQWjolrB4ZYopG9HChlCSx5y2wg5TiewNvanHVA=
    github_token:
      secure: Khm7n+BN8K0nvj9MJUnL7JDE/u3JIs1lLeVFQHJws/QfmTgEp7HNGDQ71ef97bOKl2/cIp0i+d0D+k5UbRdXIJ3IZJb2iIXXDj0ib2bDZnOA+aaOD6BZ0KSW8mjdC1p1TdcWCTIYz5zeppP5GUEH05LVPwfCmNq3xPecCOCewYhVyfa3ABtQEqGZylBJ9MizZMocSyu1q7sMBN5OuGDkPf9gWPvKMAnBWa+oTGH9DUvzvA8tYf++znRhwQOn5LeuBd2S2QPrO19IDyYm7b6aEvQx+FNAVCLCoRElWQHkbE/pvQNHctBJooI8vOVUnF4EvPmN40tETBVpQ8j8csinwlnriKcfEszwwewS9Qx5EQGoqntlEBIVNC3DlznKF4jmzcZNV2wiS+DsTajAQK7BaX2sVp+oHF3dRh0IxZn5Dg6gbYsIJZu3AtcVeQoJF8s7GttJLv/n3AhTffiOQJjEJJDXXMtL7VXyr02Z9H4g5SIh8oNHb+Cz27rsOVPqGzOXi2uYxRFRh469GzzgO/Z4uO48y3Wo0xOGyFopYluKTHhslVyX0BUGEJZHpAch2hDGLqeli4UpQ0yQXeU4w9vkoJOFOgSmTdFLEGxeLiw/vqCZg5Oe1NeLDketg+X6QyHxggDv3su/LscZWj2GJI65jq7rwz5uanxM7hv+jOwn0co=
  branches:
  - master

script:
- mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
