# see also:
# https://docs.travis-ci.com/user/sonarqube/
# https://docs.sonarqube.org/display/SONAR/User+Token
# https://travis-ci.org/orrrg/test/branches
# https://sonarqube.com/organizations/orrrg/projects

language: java
sudo: false
jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "orrrg"
    token:
      # this one is to be able to run analysis on SonarQube
      # this is only token, without variable name. only a secret
      # (this is different from when you set an environment variable)
      secure: DM3QBbsYiHRMKg90kd6CpzFPn/TGCw60VHkKYY2BBlJUfXoqDj+SWS8MmpG3WMDQ4NCNZ1YmQ3+qNv3DdQg5q9iBUT10CFfLcGar7EGtEDwu+p4E6Oi1n18pUmh9cbIRLCpNA3LHUbNAmtzgPTsWi5u9lqo+CSfsJ3eUxwsuaDFMOIdgv/gXQ5q7Zsxs9QzQgX9Gqwc9YtNMmAxa25KGSsmBVKy8Y2LcijvlwAlRBWIGw8VWOJBcBH3QPH0prqM4GAh/9eMF1p9fQEmaeorGAFTrL1BNWXIlFALxAWp0TKyyfiN6I5d8gSh9SklEQkXPphCIfH2lnyY95PcoA4eMVvShYCcTqY9N/8HpMJ+3Qtg8Krws4CL3iJp/UE3CzsxfUpGz1nyWt+a0WnTIVfkn0qQJpTMCJMJ6lxHmpHQEOYchq8WUKKbxtPuz+IHJ3c3LhCmmxhPvsirSZZH5epq4G3MTYcpxGUQl9EjFGVitor348gIqGazA0UySDtTKqnzB7Vp8qNvvnGuCxVD+K+imMhqDfoJvj+fT7TsegRO+Yq6zEdc7FC8zQP200wXVNePAAOQifBZkkRjIoThiMJXp8pnbZF4maWWT62yzZ7nTtRq/qc9gsTYtCEH/Jzny7rjRZKdQBaHsRd/oM106EExVHNew6ds+McnlSso/vokJEX0=
    github_token:
      # this one is for pull requests (to add comments on them in GitHub)
      # created with something like:
      # `travis encrypt 8bae8bae8baeb8baeby8b1`
      secure: n8tQmEBUHZGPGNygWlCUsaPiBZwGAgM5wtYgfRFh63UguwsmKPT5t1pL2Y3iAYhvVWXp3YLxP4qNGpKwIbC83C7RXCzsEiOTQDk8R4O97c4IVhyPhCxD3hEDoISjiiMdAUbXHmEOsdokks9pAN/Tnewr/ZQJQfbWe9Uc7GUcSHdg/MwClM6XoNm5jr3guNaIRrTCDLz/z0QHJE1h8NjOWaHygKP3A5PEYZdT1fGND88tFb1fQeGYLDPAx+VYTi/+ailgAGO4h7LJ0wEeF/I9wEZ3Zsx7OGrtpGIUT1itGDEwZYD9oEybs5QHSXSMT8+0j2Yxs/6dsyy6oK0EI9wP1zFUDUeqQGmgYJYcsC8LoGzRUmt2WmCZQtJgOf49H5A0xtgbp2AnXQINdk4obk4nTBmvSIvszaL/NWXU5J0oWdEwnnEvgkq9n3LCPs3MMuFUqxHlumgr8OXseWQvm8vQbpQsbfWV/TEMBiOCF84e8oAjcZJZ7BRw8NJXDtJdMFFylyDsc/EBb4jHJkcW623gj632QIBX/tDH2uJOCZqlaSZjf9JKVShw1NnDa8543hJPqC8WMdLm7fpa8w3Mw5tkRIvxNcK8P1QVtGj1EO4kMVwSDJqOOWaH6cMr2vRDy0qufuaaYZfO1UevZTNVZlzGzc6Zf9NhJB86JfQKGtLEzvI=
    branches:
    - master
    - branch

script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
- mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
