language: java
sudo: false
jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "orrrg"
    token:
      # this one is to be able to run analysis on SonarQube
      secure: PuSRCjop4ESPe4X+4CExu4M/ED9BzLskIMgbenyV5Ko3h567fBx1h5SMZtgQE6XRTdgvjYoghec//4eUiRteot3+Hyn3kZkaoLcCkcvbngiJ1nvLyCOXh/GJif8sFUNpMRORiSKwqZ54TzK6f6yeLtCMwt2NggELU0y7nJEnqYSa/VbCQJP3dDr0Ov5ubo0cp8gDTy+jZe8mC+auJHxRLaYMEbPv2XH+hf5BDf4CVQB69d6KTEOHq1xVb/MR2b5bUao8uA48w/3B1BPAnJ+IzRVWOptETaY0MN2a3Mom65gqNOfACX4VAMoBkmP/0xAFhGDplNUzYgyUCdji41X79KOt0EV6v3SXFczdhDRY3qt+JCHCmuktfOfgJc9g/GFAo76nxYSB5bcUqX9y4ug5nZbitHhT6YY3GitH+fk0l5dUi70Tyw/KAWOOti+3yEWL4R21mO/HWSnpBzP5X650UdF+iLZO8N5R9rS0tF1l2CTSCbG75acem8wst+UkYOhUZIBminlb0KXZqWNmKwJAIgvs4kttviNBnb6ZxqCtGs2ajrLDRoSUZE5mf39bCw3qYQXEixa+iXJWLZmHDQn2GMZGVHP4A0GaPXWMYkTS1intd+kgeBp4YjcGHxBIBaq3QrKNktFUc7agxQ8EedZCZ8XBaINWMs54yUOU0PZMjFo=

    github_token:
      # this one is for pull requests (to add comments on them in GitHub)
      secure: czhz7DVkptSb6V+4HgBQKErFUT1vo7i5w0WYhd7uiCRrx+R3MdP8Gizhhw9OcJF3DW/0RS3jl/YNTCbuWT5r/IcDDTqiWLzceOmWhalvcXzLOsWmfTIhVEXx99lR/BQVpsb0W4mrsMotTx1b9IKy6kAhgDywCM3zcO/BSxKLsLiaGjZcazyN3TySw9N8rr7pBrGrZV6KuJT8LesUBRqtcaPLJGwezS/UiHjEbiuVnEYhxZ8yP1ejcgXX/XfE6Ti9qFv5+u3VQYEVUX076Y4n4Y28rAhBAEBjAktloN3VRjIn+rnMOheYZMYFWhRj6IE1nATVdjehL++SIazgCFAUOoV4KmgWjUDqmkIhr3mHyDY5mPLclN+8OrHHIWSUW0UkTH7hmXeB31nI8azKCycrtH9QbH4L+Y4Lb1OZFmR6r8BBOOav51iAmQguRA/uGLxnYZM12GjTWZ+Abof6sUKv06qyDeFhBgrL290SoEJ5BxpSDM/uWb/IsboaJUEVqggPhS1FvA9WafqTdfUl+RpY9Xj7zGlLtVq/9eV0rdCrc1FNAuMVg5ftDsMWmbcZHcbwntynqA1BQfD5dSjP8/i+1yCi6zMzKIPABDTkpMLRQ9zDOW3t8SctK0s1YigZ7CVEs1VVlkBwMOyIS+BigeYgqVO5AImno5DWhy0bKBOEliA=

script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
- mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
