language: java
sudo: false
jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: "orrrg"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
