# see also:
# https://docs.travis-ci.com/user/sonarqube/
# https://docs.sonarqube.org/display/SONAR/User+Token
# https://travis-ci.org/orrrg/test/branches
# https://sonarqube.com/organizations/orrrg/projects

language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

script:
  - mvn -B clean install

addons:
  sonarcloud:
    organization: orrrg
    token:
      secure: KaeSET0OMEomrgxHYL1ickTdiAgAJ8CdvgohsEJLJo7C2WZIfrioFHT/YSRu/1BL+3W3TTLgqTIc2XjROIQstSRm0nMYDCxqhcW9/IeST/gOcWPOMxx3ymp/+rDjscFDUj3zKbcWutFiK0vYRi++o81bYVixrjcB93GuVx1++F4VjfDSSZgN3b776G87x4CXOCpmarU8kkrYnIwslkb4bXz2VBg/EacWRb1gbwY8dK0DrNmEU9n0kUGVX3MvLlWRmj0znPuLJ6CGX1cNXIlaRsYzCgukXlHr1PBAL4Gb17PeBo2zBYewm1qW6pdxR8j//wXHnzaG/vFy+wCsbCEueKxPB4Bxg/JHXELVDwbCaU+PU6t6iQ7RACX8evHhTjlnVeEXUsOcUstI4J0cJxciAFUNgqYw71x6sF1hoVzU7UWf3Z0W0ZaOPbkizCnyqKIscXfkQY9R17t45Z7BsAdnrunAGfzI0EAqszFHK8bFxM1HsT22H13e0gj+12GVgDL+MsScLin/CI4hMF5OwAdiB4sooiO5u2MyQxmF30Ll6ZmTZn/Quu9k+zOLZtWxUQmKZwXwDt3it0S8QjJ90wiw6DOvQ0qca9ql2Md0GGHpbasPjxgJcf+ymXdwiRvS8K4A3dUOZAXGMG4PGR7Xe8X2Ulw8sONh7LeFTTe1KL3WGSM=

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
