language: java
sudo: false
jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: orrrg
    token:
      # this one is to be able to run analysis on SonarQube
      secure: bUMq7V8144PiwD0GdJxF6vHTt6BoAW558IlX9IKEH9dA++oSu7tTacC22gMDBGqwy6SbZWhbU6jK0xSfEyIq34dC5E6D8rZtJPCRvekkmw4GMNyN3uOLDRD6dxjmFIEv8IC4a8bb6H/rQjePQWgSsQQw4HzOMTQzcOWV+KhPhAxhoFbU0J/5VseCBvqnGS6/5to+GTlNXXG5wr/eBsvDSwIXwBqhvwcQZjZRwyichxcw7fG+k1ZHVbjYJptKaqjUgSg2vQ5jXNvGDXyBrb7xXOxP0BYwpA+a+PoQs4mQNqf0j1xOnEBuKhIgDSnbWLItgazQE0zo/EpI1bkoYhCMQlWHLB/B6sgZJ0mrusGYkEuH2Auxfx2dwaigYmkOplrGfyBxv/fU2AAkgxUhSHNE+83Pfb0iSjRznTElQduQVMc01Kkt69sonwyIpGGKSiMnSj9U4Pz1zxLwB2g6txoYybgzodWhDVTYPSUowMgCzbIgKc8TJor3RBvXrCJtC0JHFAaUNzTODBskGEbl6+zTN+Id1cJjaeXtHI/ViLE2oRrquUN6KflTA5iyKHPDiNYYOnybsIxUyyH0pUwoZI3+5JHX5ggXKy1Y9f7n7LXUHwA8l+BlvdS2l7w9EY2cCfwr4toOyQWjolrB4ZYopG9HChlCSx5y2wg5TiewNvanHVA=
    github_token:
      # this one is for pull requests (to add comments on them in GitHub)
      secure: czhz7DVkptSb6V+4HgBQKErFUT1vo7i5w0WYhd7uiCRrx+R3MdP8Gizhhw9OcJF3DW/0RS3jl/YNTCbuWT5r/IcDDTqiWLzceOmWhalvcXzLOsWmfTIhVEXx99lR/BQVpsb0W4mrsMotTx1b9IKy6kAhgDywCM3zcO/BSxKLsLiaGjZcazyN3TySw9N8rr7pBrGrZV6KuJT8LesUBRqtcaPLJGwezS/UiHjEbiuVnEYhxZ8yP1ejcgXX/XfE6Ti9qFv5+u3VQYEVUX076Y4n4Y28rAhBAEBjAktloN3VRjIn+rnMOheYZMYFWhRj6IE1nATVdjehL++SIazgCFAUOoV4KmgWjUDqmkIhr3mHyDY5mPLclN+8OrHHIWSUW0UkTH7hmXeB31nI8azKCycrtH9QbH4L+Y4Lb1OZFmR6r8BBOOav51iAmQguRA/uGLxnYZM12GjTWZ+Abof6sUKv06qyDeFhBgrL290SoEJ5BxpSDM/uWb/IsboaJUEVqggPhS1FvA9WafqTdfUl+RpY9Xj7zGlLtVq/9eV0rdCrc1FNAuMVg5ftDsMWmbcZHcbwntynqA1BQfD5dSjP8/i+1yCi6zMzKIPABDTkpMLRQ9zDOW3t8SctK0s1YigZ7CVEs1VVlkBwMOyIS+BigeYgqVO5AImno5DWhy0bKBOEliA=

script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
- mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
